- hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"  
  pre_tasks:
    - name: Sync Repositories (Update Packages)
      become: yes
      pacman:
        update_cache: yes
        state: present
      tags:
        - install
        - core
        - git
  tasks:
    - include_tasks: ./tasks/core-pkgs.yml
    - include_tasks: ./tasks/git-setup.yml
    - include_tasks: ./tasks/fish-setup.yml
    - include_tasks: ./tasks/node-setup.yml
